### ISSUE TITLE
Unable to run the Project. 

### ISSUE THREAD

**Issue by shahryar-cmyk** [aloistr/perl-sweph#4]
Here is the code of the Makefile.PL 
Error I am facing is 
`
Warning (mostly harmless): No library found for C:/swisseph-master/swisseph-master/windows/sweph/sweph/bin/swedll64.dll
Warning (mostly harmless): No library found for -lswe
Warning (mostly harmless): No library found for -lmoldname
Warning (mostly harmless): No library found for -lkernel32
Warning (mostly harmless): No library found for -luser32
Warning (mostly harmless): No library found for -lgdi32
Warning (mostly harmless): No library found for -lwinspool
Warning (mostly harmless): No library found for -lcomdlg32
Warning (mostly harmless): No library found for -ladvapi32
Warning (mostly harmless): No library found for -lshell32
Warning (mostly harmless): No library found for -lole32
Warning (mostly harmless): No library found for -loleaut32
Warning (mostly harmless): No library found for -lnetapi32
Warning (mostly harmless): No library found for -luuid
Warning (mostly harmless): No library found for -lws2_32
Warning (mostly harmless): No library found for -lmpr
Warning (mostly harmless): No library found for -lwinmm
Warning (mostly harmless): No library found for -lversion
Warning (mostly harmless): No library found for -lodbc32
Warning (mostly harmless): No library found for -lodbccp32
Warning (mostly harmless): No library found for -lcomctl32
Generating a gmake-style Makefile
Writing Makefile for SwissEph
Writing MYMETA.yml and MYMETA.json
`
```
#!/usr/local/bin/perl
use 5.016003;
use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
#
# to build statically linked SwissEphe.so, call
# perl Makefile.PL LIBS='' MYEXTLIB='/home/swehome/libswe.a'

WriteMakefile(
    NAME              => 'SwissEph',
    VERSION_FROM      => 'lib/SwissEph.pm', # finds $VERSION
    PREREQ_PM         => {}, # e.g., Module::Name => 1.1
    ABSTRACT_FROM  => 'lib/SwissEph.pm', # retrieve abstract from module
    AUTHOR         => 'Alois Treindl <alois@astro.ch>',
    # LIBS              => ['-L/usr/local/lib64/swe -lswe'], 
    LIBS              => ['C:/swisseph-master/swisseph-master/windows/sweph/sweph/bin/swedll64.dll -lswe'],
    # MYEXTLIB     => '/home/swehome/libswe$(LIB_EXT)',
    DEFINE            => '', # e.g., '-DHAVE_SOMETHING'
    INC               => '-I.', # e.g., '-I. -I/usr/include/other'
    DISTVNAME         => 'perl_sweph', # 
    # OBJECT            => '$(O_FILES)' . "$O_FILES", # link all the C files too

);

sub MY::postamble {
'
$(MYEXTLIB): /home/swehome/Makefile
	cd /home/swehome && $(MAKE) libswe.a $(PASSTHRU)
';
}

```

**Comment by aloistr** [comment]
Sorry, I cannot support Windows issues. Please move to Linux.
